package db;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * Created by Aesraethr on 23/07/2015.
 */
@DynamoDBTable(tableName = "littering-config")
public class Config {

    private String id;
    private boolean moderation;

    public Config() {
    }

    public Config(String id, boolean moderation) {
        this.id = id;
        this.moderation = moderation;
    }

    public Config(boolean moderation) {
        this.moderation = moderation;
    }

    @DynamoDBHashKey(attributeName = "id")
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "Moderation")
    public boolean isModeration() {
        return moderation;
    }
    public void setModeration(boolean moderation) {
        this.moderation = moderation;
    }
}
